@echo off
echo ---------------------------------------------------------------------------
echo - ROM Font Replacer Test - Checksum Update (rfrtestu.bat)                 -
echo - Copyright (C) 1998-2020 Alexandru Groza of Microprogramming TECHNIQUES  -
echo - All rights reserved.                                                    -
echo ---------------------------------------------------------------------------
echo - License: GNU General Public License v3.0                                -
echo ---------------------------------------------------------------------------

romfontr.exe -u -romfile=vga.bin -fontfile=ag86font.bin
echo.
